/* Private admin-only enrichment; credentials and PINs are never requested or rendered. */
(function () {
  'use strict';
  var root='/api/v1/admin/device-manager', page=1, generation=0, openRecord, installed=false, lastItems=[];
  var labels={trial:'تجربة سارية',active:'مفعّل',expired:'منتهي',blocked:'موقوف'};
  var errors={device_changed:'تغيّرت بيانات الجهاز. حدّث السجل قبل إعادة الحفظ.',device_restore_unavailable:'هذا الإيقاف قديم ولا يوجد سجل آمن للحالة السابقة؛ لم نغيّر التفعيل.',invalid_device_edit:'راجع البيانات المدخلة.',invalid_device_email:'البريد الإلكتروني غير صحيح.',rate_limited:'طلبات كثيرة؛ انتظر قليلًا وأعد المحاولة.'};
  var $=function(id){return document.getElementById(id);};
  function el(tag,text,cls){var e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;}
  function date(n){return n==null?'غير مسجل':new Date(n).toLocaleString('ar-SA',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});}
  function status(text,bad){$('admin-status').textContent=text;$('admin-status').classList.toggle('bad',!!bad);}
  async function api(path,method,body){var controller=new AbortController(),timer=setTimeout(function(){controller.abort();},15000);try{var r=await fetch(path,{method:method||'GET',credentials:'same-origin',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:controller.signal});if(r.status===401){location.assign('/admin');throw Error('انتهت جلسة الإدارة.');}var data=await r.json();if(!r.ok)throw Error(errors[data.error]||'تعذر إكمال الطلب. أعد المحاولة.');return data;}catch(e){if(e.name==='AbortError')throw Error('تأخر رد الخدمة. بياناتك لم تُحذف؛ أعد المحاولة.');throw e;}finally{clearTimeout(timer);}}
  function select(name,label,options){var field=el('label',label),s=el('select');s.name=name;options.forEach(function(o){var x=el('option',o[1]);x.value=o[0];s.append(x);});field.append(s);return field;}
  function setup(){if(installed)return;installed=true;var form=$('customer-search');
    form.append(select('filter','تصفية الأجهزة',[['all','كل الأجهزة'],['new24h','جديد خلال 24 ساعة'],['new7d','جديد خلال 7 أيام'],['trial','التجربة سارية'],['active','التفعيل ساري'],['expired','منتهٍ'],['blocked','موقوف'],['noPlaylists','بدون قوائم'],['recent','تواصل خلال 10 دقائق'],['inactive7d','لم يتواصل منذ 7 أيام'],['expiring7d','ينتهي خلال 7 أيام']]));
    form.append(select('sort','الترتيب',[['newest','الأحدث تسجيلًا'],['seen','آخر تواصل'],['expiry','الأقرب انتهاءً']]));var field=el('label','نسخة العميل المسجلة'),input=el('input');input.name='version';input.placeholder='مثال: 2.0.0-rc07.40';field.append(input);form.append(field);
    form.addEventListener('input',function(){page=1;});form.addEventListener('change',function(event){page=1;if(event.target.tagName==='SELECT')customers(openRecord);});
    var head=form.parentElement.querySelector('thead tr');head.replaceChildren();['العميل / الجهاز','التفعيل','أول تسجيل','الانتهاء','آخر تواصل','النسخة','القوائم','الإدارة'].forEach(function(t){head.append(el('th',t));});
    var counts=el('p','','caption');counts.id='device-insights-counts';form.before(counts);var bar=el('div',null,'actions');bar.id='device-pages';
    [['device-prev','السابق',-1],['device-next','التالي',1]].forEach(function(x){var b=el('button',x[1]);b.type='button';b.id=x[0];b.addEventListener('click',function(){page+=x[2];customers(openRecord);});bar.append(b);});var info=el('span','','caption');info.id='device-page-info';bar.append(info);form.parentElement.append(bar);
    var foot=$('devices-view').querySelector('.admin-foot');if(foot)foot.textContent='«جديد» حسب أول تسجيل لدى الخدمة، وليس تاريخ تنزيل التطبيق. آخر تواصل قد يكون من البوابة، ولا يعني اتصالًا مباشرًا الآن. حفظ القائمة بالموقع لا يؤكد وصولها للجهاز.';
  }
  async function customers(callback){openRecord=callback;setup();var current=++generation;var q=new URLSearchParams(new FormData($('customer-search')));q.set('page',String(page));status('جارٍ تحديث الأجهزة…');$('device-prev').disabled=true;$('device-next').disabled=true;try{var data=await api(root+'?'+q.toString());if(current!==generation)return;lastItems=data.items;var rows=$('customer-rows');rows.replaceChildren();data.items.forEach(function(item){var tr=el('tr'),name=el('td');name.append(el('strong',item.name||item.deviceId));if(item.name)name.append(el('div',item.deviceId,'caption'));if(item.isNew)name.append(el('span','جديد خلال 24 ساعة','badge new-device'));var action=el('td'),button=el('button','إدارة ←');button.addEventListener('click',function(){openRecord(item.deviceId);});action.append(button);tr.append(name,el('td',labels[item.status]||item.status),el('td',date(item.firstSeenAt)),el('td',item.expiresAt==null?(item.status==='active'?'مدى الحياة':'—'):date(item.expiresAt)),el('td',date(item.lastSeenAt)),el('td',item.clientVersion||'غير مسجل','version-cell'),el('td',String(item.playlistCount)),action);rows.append(tr);});if(!data.items.length){var tr=el('tr'),td=el('td','لا توجد أجهزة مطابقة.');td.colSpan=8;tr.append(td);rows.append(tr);}var counts=data.counts;$('device-insights-counts').textContent='كل الأجهزة: '+counts.total+' · جديد خلال 24 ساعة: '+counts.new24h+' · خلال 7 أيام: '+counts.new7d+' · تواصل حديث: '+counts.recent;$('device-page-info').textContent='الصفحة '+data.page+' · '+data.total+' جهاز مطابق';$('device-prev').disabled=page<=1;$('device-next').disabled=page*data.pageSize>=data.total;status('');}catch(e){if(current===generation){status(e.message,true);$('device-prev').disabled=page<=1;}}}
  function definition(pairs){var list=el('dl');pairs.forEach(function(p){list.append(el('dt',p[0]),el('dd',p[1]==null?'غير مسجل':String(p[1])));});return list;}
  async function record(id,isCurrent,onChange){var old=$('device-admin-extra');if(old)old.remove();var box=el('section',null,'card device-insights');box.id='device-admin-extra';$('record-summary').parentElement.after(box);box.append(el('h3','معلومات الجهاز وخياراته'),el('p','جارٍ قراءة التفاصيل…','caption'));
    try{var data=await api(root+'/'+encodeURIComponent(id));if(!isCurrent()||!box.isConnected)return;box.replaceChildren(el('h3','معلومات الجهاز وخياراته'),definition([['أول تسجيل لدى الخدمة',date(data.firstSeenAt)],['بداية التجربة',date(data.trialStartedAt)],['المدة المتبقية',data.remainingDays==null?(data.status==='active'?'مدى الحياة':'—'):data.remainingDays+' يوم'],['عدد القوائم في الموقع',data.playlistCount],['القائمة النشطة في الموقع',data.activePlaylist||'لا توجد'],['آخر حفظ لقائمة',date(data.playlistUpdatedAt)],['المنصة المبلغ عنها',data.platform||'غير مسجلة'],['آخر عميل تواصل',data.clientVersion||'غير مسجل'],['قفل محاولات الربط',data.authLockedUntil&&data.authLockedUntil>Date.now()?date(data.authLockedUntil):'غير مقفل']]));
      box.append(el('p','أول تسجيل لا يثبت وقت التثبيت. عدد القوائم وتاريخ حفظها يخصان الموقع، وليس تأكيدًا بمزامنة الجهاز.','caption'));
      var tools=el('div',null,'actions'),copy=el('button','نسخ رقم الجهاز');copy.type='button';copy.addEventListener('click',async function(){try{await navigator.clipboard.writeText(id);copy.textContent='تم النسخ';}catch(e){window.prompt('رقم الجهاز',id);}});tools.append(copy);
      var block=el('button',data.rawStatus==='blocked'?'إلغاء الإيقاف':'إيقاف تفعيل الجهاز','danger');block.type='button';tools.append(block);box.append(tools);var message=el('p','','status');message.setAttribute('role','status');box.append(message);
      block.addEventListener('click',async function(){if(!isCurrent())return;var action=data.rawStatus==='blocked'?'unblock':'block';if(!window.confirm((action==='block'?'إيقاف تفعيل ':'استعادة حالة التفعيل السابقة لـ ')+id+'؟\nلن تُحذف قوائمه أو يتغيّر تاريخ الانتهاء. تطبيق القرار يتطلب تواصل الجهاز مع الخدمة.'))return;block.disabled=true;try{await api(root+'/'+encodeURIComponent(id)+'/status','POST',{action:action,expectedStatus:data.rawStatus,expectedExpiresAt:data.expiresAt});if(isCurrent())onChange();}catch(e){message.textContent=e.message;block.disabled=false;}});
      var form=el('form',null,'device-profile');form.append(el('h3','بيانات العميل وملاحظاتك'));[['name','اسم العميل',120],['phone','رقم الجوال',32],['email','البريد الإلكتروني',254],['notes','ملاحظات داخلية',2000]].forEach(function(x){var field=el('label',x[1]),input=el(x[0]==='notes'?'textarea':'input');input.name=x[0];input.maxLength=x[2];if(x[0]==='notes')input.rows=3;if(x[0]==='email')input.type='email';input.value=data[x[0]]||'';field.append(input);form.append(field);});var save=el('button','حفظ بيانات العميل','primary');save.type='submit';form.append(save);var saveStatus=el('p','','status');saveStatus.setAttribute('role','status');form.append(saveStatus);form.addEventListener('submit',async function(event){event.preventDefault();if(!isCurrent())return;save.disabled=true;block.disabled=true;saveStatus.textContent='جارٍ الحفظ…';try{var payload=Object.fromEntries(new FormData(form));payload.expectedRevision=data.revision;await api(root+'/'+encodeURIComponent(id),'PATCH',payload);if(isCurrent())onChange();}catch(e){saveStatus.textContent=e.message;save.disabled=false;block.disabled=false;}});box.append(form);
    }catch(e){if(isCurrent()&&box.isConnected){box.replaceChildren(el('p',e.message,'status bad'));var retry=el('button','إعادة تحميل التفاصيل');retry.type='button';retry.addEventListener('click',function(){record(id,isCurrent,onChange);});box.append(retry);}}
  }
  window.BlofyDeviceAdmin={customers:customers,record:record};
}());
