package tv.blofy.player.ui.common
import android.graphics.Color
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.view.View
import android.widget.TextView
object BlofyTvDesign {
 val Background=Color.rgb(10,8,16);val BackgroundRaised=Color.rgb(17,13,25);val Surface=Color.rgb(25,20,34);val SurfaceRaised=Color.rgb(32,25,43);val SurfaceFocused=Color.rgb(75,42,112);val Purple=Color.rgb(130,69,218);val PurpleBright=Color.rgb(174,105,255);val PurpleDeep=Color.rgb(67,35,101);val PurpleSoft=Color.rgb(205,177,236);val Lavender=Color.rgb(222,205,239);val Mint=Color.rgb(82,216,181);val Error=Color.rgb(255,112,135);val TextPrimary=Color.rgb(249,247,252);val TextSecondary=Color.rgb(218,212,226);val TextMuted=Color.rgb(157,149,169);val Divider=Color.rgb(53,44,64)
 const val HeroTitleSp=40f;const val DetailTitleSp=40f;const val TitleSp=31f;const val HeadingSp=20f;const val BodySp=15f;const val LabelSp=14.5f;const val CaptionSp=12f
 const val ScreenPadding=28;const val PanelPadding=14;const val RailWidth=250;const val CategoryRowHeight=60;const val LiveListWidth=455;const val CardRadius=20;const val PanelRadius=24;const val ButtonRadius=18;const val BadgeRadius=12;const val StandardGap=20;const val FocusInMs=92L;const val FocusOutMs=72L;const val SectionTransitionMs=115L
 val DisplayTypeface:Typeface by lazy{Typeface.create("sans-serif",Typeface.BOLD)};val HeadingTypeface:Typeface by lazy{Typeface.create("sans-serif",Typeface.BOLD)};val LabelTypeface:Typeface by lazy{Typeface.create("sans-serif-medium",Typeface.BOLD)};val BodyTypeface:Typeface by lazy{Typeface.create("sans-serif",Typeface.NORMAL)};val MediumTypeface:Typeface by lazy{Typeface.create("sans-serif-medium",Typeface.NORMAL)}
 fun surface(radius:Float=CardRadius.toFloat(),focused:Boolean=false)=GradientDrawable(GradientDrawable.Orientation.TL_BR,if(focused)intArrayOf(0xFF56317C.toInt(),0xFF24172F.toInt())else intArrayOf(0xF21D1727.toInt(),0xF214101B.toInt())).apply{cornerRadius=radius;setStroke(if(focused)2 else 1,if(focused)PurpleBright else 0xFF392E46.toInt())}
 fun glassSurface(radius:Float=CardRadius.toFloat(),focused:Boolean=false)=GradientDrawable(GradientDrawable.Orientation.TL_BR,if(focused)intArrayOf(0xE6533078.toInt(),0xE81C1427.toInt())else intArrayOf(0xD91C1724.toInt(),0xE6110E17.toInt())).apply{cornerRadius=radius;setStroke(if(focused)2 else 1,if(focused)0xFFCFA7FF.toInt() else 0x66483A58)}
 fun elevatedSurface(radius:Float=PanelRadius.toFloat())=GradientDrawable(GradientDrawable.Orientation.TL_BR,intArrayOf(0xF5221B2D.toInt(),0xF514101B.toInt())).apply{cornerRadius=radius;setStroke(1,0xFF3D304A.toInt())}
 fun primaryButton(radius:Float=ButtonRadius.toFloat(),focused:Boolean=false)=GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,if(focused)intArrayOf(0xFFAE69FF.toInt(),0xFF7540C7.toInt())else intArrayOf(0xFF8245DA.toInt(),0xFF5B2CA3.toInt())).apply{cornerRadius=radius;setStroke(if(focused)2 else 1,if(focused)0xFFF0DFFF.toInt() else 0xFF9363C3.toInt())}
 fun secondaryButton(radius:Float=ButtonRadius.toFloat(),focused:Boolean=false)=glassSurface(radius,focused);fun badge(radius:Float=BadgeRadius.toFloat())=GradientDrawable().apply{cornerRadius=radius;setColor(0xCC251B31.toInt());setStroke(1,0xFF604A75.toInt())}
 fun applyTitle(t:TextView)=t.apply{textSize=TitleSp;typeface=DisplayTypeface;setTextColor(TextPrimary);includeFontPadding=false};fun applyHeroTitle(t:TextView)=t.apply{textSize=HeroTitleSp;typeface=DisplayTypeface;setTextColor(TextPrimary);includeFontPadding=false;letterSpacing=-.01f};fun applyHeading(t:TextView)=t.apply{textSize=HeadingSp;typeface=HeadingTypeface;setTextColor(TextPrimary);includeFontPadding=false};fun applyBody(t:TextView)=t.apply{textSize=BodySp;typeface=BodyTypeface;setTextColor(TextSecondary);includeFontPadding=false;setLineSpacing(0f,1.16f)};fun applyLabel(t:TextView)=t.apply{textSize=LabelSp;typeface=LabelTypeface;setTextColor(TextPrimary);includeFontPadding=false};fun applyCaption(t:TextView)=t.apply{textSize=CaptionSp;typeface=MediumTypeface;setTextColor(TextMuted);includeFontPadding=false}
 fun installTvFocus(v:View,radius:Float=CardRadius.toFloat(),scale:Float=1.025f,primary:Boolean=false,onFocused:(()->Unit)?=null){v.isFocusable=true;v.isFocusableInTouchMode=true;v.background=if(primary)primaryButton(radius,false)else secondaryButton(radius,false);(v as? TextView)?.setTextColor(TextPrimary);v.setOnFocusChangeListener{x,f->x.background=if(primary)primaryButton(radius,f)else secondaryButton(radius,f);(x as? TextView)?.setTextColor(TextPrimary);x.animate().cancel();x.animate().scaleX(if(f)scale else 1f).scaleY(if(f)scale else 1f).translationZ(if(f)16f else 2f).alpha(if(f)1f else .97f).setDuration(if(f)FocusInMs else FocusOutMs).start();if(f)onFocused?.invoke()}}
}
